import type { Metadata } from "next";
import { Sora} from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/custom";
import Authprovider from "../app/components/Authprovider"
import Script from 'next/script'
import {CartProvider} from "../app/components/context"


export const metadata: Metadata = {
  title: "Vaayusastra Aerospace",
  description: "Generated by create next app",
};
const sora=Sora({
  subsets: ["latin"],
  weight:["300","400","500","600","700","800"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
    <html lang="en">
      <body className={sora.className}>
        
         <Authprovider >
          <CartProvider>

            <CustomCursor />
            {children}
          </CartProvider>
         </Authprovider>
         
      </body>
    </html>
    <Script src="https://checkout.razorpay.com/v1/checkout.js"/>
  </>
  );
}
